/// Scaffold string for `graydr init module`.
///
/// This constant is a valid `.gmod` file that passes `parse_module_file`.
/// It contains placeholder content and inline comments pointing to the
/// Module Authoring Guide. Two provider case arms (aws, azure) are
/// included as a starting point.
#[allow(dead_code)]
pub const SCAFFOLD_MODULE: &str = r#"# Generated by `graydr init module`
# See the Module Authoring Guide for complete documentation.
module "my_module" {
  metadata {
    description = "TODO: describe what this module does"
    version     = "0.1.0"
  }

  interface {
    inputs {
      my_variable = {
        required  = true
        sensitive = false
      }
    }
    outputs {
    }
  }

  validation {
  }

  generate {
    case "provider" {
      aws {
        code = <<-EOT
          # TODO: write Terraform/CloudFormation HCL here
          # Use $my_variable for graydr variables
        EOT
        outputs {
        }
      }
      azure {
        code = <<-EOT
          # TODO: write Bicep/ARM HCL here
        EOT
        outputs {
        }
      }
    }
  }
}
"#;

/// Scaffold string for `graydr init template`.
///
/// This constant is a valid `.gtpl` file that passes `parse_template_file`.
/// It contains placeholder content and inline comments for a simple
/// single-resource template.
#[allow(dead_code)]
pub const SCAFFOLD_TEMPLATE: &str = r#"# Generated by `graydr init template`
# See the Template Authoring Guide for complete documentation.
template "my_template" {
  metadata {
    description = "TODO: describe what this template does"
    version     = "0.1.0"
  }

  parameters {
    config {
      provider = {}
      region   = {}
    }
  }

  resource "main" {
    module = "my_module"
    inputs {
      my_variable = "$config.provider"
    }
  }

  outputs {
  }
}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::module::parse_module_file;
    use crate::parser::template::parse_template_file;

    #[test]
    fn test_scaffold_module_parses() {
        parse_module_file(SCAFFOLD_MODULE, "scaffold.gmod").unwrap();
    }

    #[test]
    fn test_scaffold_template_parses() {
        parse_template_file(SCAFFOLD_TEMPLATE, "scaffold.gtpl").unwrap();
    }
}
